spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account?serverTimezone=GMT%2B8
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
    schema-password: root
    schema-username: root
    data-password: root
    data-username: root

