
spring:
  redis:
    dbIndex: 0
    hostName: 192.168.58.133
    password: nmamtf
    port: 6379
    timeout: 0
    poolConfig:
        maxIdle: 8
        minIdle: 0
        maxActive: 8
        maxWait: -1
  profiles:
    active: dev

profiles: default


enableName: enableName
enableSex: enableSex
